# -*- coding: utf-8 -*-
"""Cópia de Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SrvcMnwKM30rNC-o2WiNkgsrKnF3UcYg
"""

#Escreva um programa python que solicita as 3 notas de um aluno, calcula a média e informa se o aluno passou ou ficou em recuperação (a média para passar é 7)
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
media = (nota1 + nota2 + nota3) / 3
if media >= 7:
    print(f"O aluno passou com média {media:.2f}")
else:
    print(f"O aluno ficou em recuperação com média {media:.2f}")

